language: python

services:
  - docker

python: 
  - 3.6
  
script:
  - cd testing/
  - DOCKER_RUN_FLAGS=--detach make run
  - python -m pip install --upgrade pip
  - python -m pip install --requirement requirements.txt

  - docker ps
  - /sbin/ifconfig

  # Wait until the port is open
  - bash -c 'until printf "" 2>>/dev/null >>/dev/tcp/$0/$1; do sleep 1; done' localhost 7011
  # ... but also wait for logstash to get started. It's slow.
  - sleep 60

  - make test
